name: CI - Run tests

on:
  push:
    branches: [ "master", "**" ]
  pull_request:
    branches: [ "master", "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/alurafake_test?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven local repo
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL on 127.0.0.1:3306..."
          for i in {1..60}; do
            if (echo > /dev/tcp/127.0.0.1/3306) >/dev/null 2>&1; then
              echo "MySQL port is open"
              break
            fi
            sleep 1
          done
          sleep 2

      - name: Run tests
        run: mvn -B -DskipTests=false test
